apiVersion: v1
kind: Service
metadata:
  name: milvus-nlb
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  ports:
  - name: milvus
    port: 19530
    targetPort: 19530
    protocol: TCP
  - name: metrics
    port: 9091
    targetPort: 9091
    protocol: TCP
  selector:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: milvus-operator
    app.kubernetes.io/name: milvus
    "milvus.io/service": "true"
