apiVersion: v1
kind: Secret
metadata:
  name: llm-credentials
type: Opaque
data:
  # Base64 encoded value of your API key
  # Replace with: echo -n "your-api-key" | base64
  api-key: c2stMTIzNA==  # This is "sk-1234" encoded
