AWSTemplateFormatVersion: '2010-09-09'
Description: '(SO9259) - Guidance for Scalable Model Inference and Agentic AI using Efficient and Accelerated Compute on Amazon EKS'

Outputs:
  ProjectStatus:
    Description: 'Project initialization status'
    Value: 'Starting the Agentic AI project'
