---
# https://karpenter.sh/docs/concepts/scheduling/
# https://karpenter.sh/docs/concepts/nodepools/
# aws ssm get-parameters --names /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2 --region us-east-1 
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: cpu-inference
spec:
  limits:
    cpu: 512
    memory: 8192Gi
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s

  template:
    metadata:
      labels:
        model-inferencing: "cpu"
        ray-control-plane: "false"

    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: cpu-inference
      taints:
        - key: "model-inferencing"
          value: "cpu"
          effect: NoSchedule
      expireAfter: 1h

      requirements:
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
          - c
          - m
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-size
          operator: NotIn
          values: [nano, micro, small, medium]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["5"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["c6i"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["c6i.4xlarge"]

---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: cpu-inference
spec:
    kubelet:
      podsPerCore: 2
      maxPods: 20
      systemReserved:
        cpu: 100m
        memory: 100Mi
    subnetSelectorTerms:
      - tags:
          eksctl.cluster.k8s.io/v1alpha1/cluster-name: "llm-eks-cluster"

    securityGroupSelectorTerms:
      - tags:
          eksctl.cluster.k8s.io/v1alpha1/cluster-name: "llm-eks-cluster"


    amiFamily: "AL2023"
    amiSelectorTerms:
      - name: "amazon-eks-node-al2023-x86_64-standard-1.31-v*"

    role: eksctl-fm-eks-cluster-nodegroup-ng-NodeInstanceRole-a4PeXoAuWu6p
    tags:
      model-inferencing: "cpu"
      ray-control-plane: "false"
    
    detailedMonitoring: true
    
    blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        iops: 10000
        encrypted: false
        deleteOnTermination: true
        throughput: 256
