apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: strandsdk-rag
data:
  .env: |
    # LiteLLM Configuration for Reasoning Models
    LITELLM_BASE_URL=http://your-litellm-loadbalancer.us-east-1.elb.amazonaws.com/v1
    REASONING_MODEL=vllm-server-qwen3
    
    # Embedding Configuration (separate from reasoning)
    EMBEDDING_BASE_URL=http://your-litellm-loadbalancer.us-east-1.elb.amazonaws.com/v1/embeddings
    EMBEDDING_MODEL=llamacpp-embedding
    
    # AWS Configuration  
    AWS_REGION=us-east-1
    OPENSEARCH_ENDPOINT=https://your-opensearch-domain.us-east-1.es.amazonaws.com
    
    # Tavily MCP Service Configuration
    TAVILY_MCP_SERVICE_URL=http://tavily-mcp-service:8001/mcp
    
    # Optional: Langfuse for observability
    LANGFUSE_HOST=http://your-langfuse-loadbalancer.us-east-1.elb.amazonaws.com
    
    # Application Settings
    KNOWLEDGE_DIR=knowledge
    OUTPUT_DIR=output
    VECTOR_INDEX_NAME=knowledge-embeddings
    TOP_K_RESULTS=3
  
  # Individual config values for environment variables
  litellm-base-url: "http://your-litellm-loadbalancer.us-east-1.elb.amazonaws.com/v1"
  reasoning-model: "vllm-server-qwen3"
  embedding-base-url: "http://your-litellm-loadbalancer.us-east-1.elb.amazonaws.com/v1/embeddings"
  embedding-model: "llamacpp-embedding"
  opensearch-endpoint: "https://your-opensearch-domain.us-east-1.es.amazonaws.com"
  aws-region: "us-east-1"
  vector-index-name: "knowledge-embeddings"
  tavily-mcp-service-url: "http://tavily-mcp-service:8001/mcp"
  langfuse-host: "http://your-langfuse-loadbalancer.us-east-1.elb.amazonaws.com"
  knowledge-dir: "knowledge"
  output-dir: "output"
  top-k-results: "3"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    app: strandsdk-rag
type: Opaque
data:
  # Base64 encoded secrets - replace with your actual base64 encoded values
  # To encode: echo -n "your-api-key" | base64
  litellm-api-key: <BASE64_ENCODED_LITELLM_API_KEY>
  embedding-api-key: <BASE64_ENCODED_EMBEDDING_API_KEY>
  tavily-api-key: <BASE64_ENCODED_TAVILY_API_KEY>
  langfuse-public-key: <BASE64_ENCODED_LANGFUSE_PUBLIC_KEY>
  langfuse-secret-key: <BASE64_ENCODED_LANGFUSE_SECRET_KEY>
