---
# Graviton Node Pool for ARM-based workloads
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: graviton-inference
spec:
  limits:
    cpu: 512
    memory: 4096Gi
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30m
  template:
    metadata:
      labels:
        model-inferencing: "graviton-inference"
        ray-control-plane: "false"
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: graviton-inference
      expireAfter: 8h
      requirements:
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
          - c
          - m
          - r
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["6"]
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: graviton-inference
spec:
  kubelet:
    podsPerCore: 2
    maxPods: 20
    systemReserved:
      cpu: 100m
      memory: 100Mi
  subnetSelectorTerms:
    - tags:
        Environment: dev
        Name: ${CLUSTER_NAME}-private-*
        karpenter.sh/discovery: ${CLUSTER_NAME}
  securityGroupSelectorTerms:
    - tags:
        Environment: dev
        karpenter.sh/discovery: ${CLUSTER_NAME}
  amiFamily: "AL2023"
  amiSelectorTerms:
    - name: "amazon-eks-node-al2023-arm64-standard-1.33-*"
  role: KarpenterNode-${CLUSTER_NAME}
  tags:
    Environment: dev
    karpenter.sh/discovery: ${CLUSTER_NAME}
    model-inferencing: "graviton-inference"
    ray-control-plane: "false"
    Provisioned-By: aws-solutions-library-samples/guidance-for-automated-provisioning-of-application-ready-amazon-eks-clusters
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        iops: 10000
        encrypted: false
        deleteOnTermination: true
        throughput: 256
