---
# x86 Node Pool for x86-based workloads
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: x86-inference
spec:
  limits:
    cpu: 512
    memory: 4096Gi
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s
  template:
    metadata:
      labels:
        model-inferencing: "x86-inference"
        ray-control-plane: "false"
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: x86-inference
      taints:
        - key: "model-inferencing"
          value: "x86-inference"
          effect: NoSchedule
      expireAfter: 8h
      requirements:
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
          - c
          - m
          - r
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["6"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: x86-inference
spec:
  kubelet:
    podsPerCore: 2
    maxPods: 20
    systemReserved:
      cpu: 100m
      memory: 100Mi
  subnetSelectorTerms:
    - tags:
        Environment: dev
        Name: wre-dev-private-*
        karpenter.sh/discovery: wre-dev
  securityGroupSelectorTerms:
    - tags:
        Environment: dev
        karpenter.sh/discovery: wre-dev
  amiFamily: "AL2023"
  amiSelectorTerms:
    - name: "amazon-eks-node-al2023-x86_64-standard-1.29-*"
  role: KarpenterNode-wre-dev
  tags:
    Environment: dev
    karpenter.sh/discovery: wre-dev
    model-inferencing: "x86-inference"
    ray-control-plane: "false"
    Provisioned-By: aws-solutions-library-samples/guidance-for-automated-provisioning-of-application-ready-amazon-eks-clusters
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        encrypted: false
        deleteOnTermination: true
