---
# Inf2 Node Pool for ML inference workloads
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: inf2-inference
spec:
  limits:
    cpu: 512
    memory: 4096Gi
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s
  template:
    metadata:
      labels:
        model-inferencing: "inf2-inference"
        ray-control-plane: "false"
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: inf2-inference
      taints:
        - key: "model-inferencing"
          value: "inf2-inference"
          effect: NoSchedule
      expireAfter: 8h
      requirements:
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["inf2"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-accelerator-manufacturer
          operator: In
          values: ["aws"]
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: inf2-inference
spec:
  kubelet:
    podsPerCore: 2
    maxPods: 20
    systemReserved:
      cpu: 500m
      memory: 900Mi
  subnetSelectorTerms:
    - tags:
        Environment: dev
        Name: wre-dev-private-*
        karpenter.sh/discovery: wre-dev
  securityGroupSelectorTerms:
    - tags:
        Environment: dev
        karpenter.sh/discovery: wre-dev
  amiFamily: "AL2023"
  amiSelectorTerms:
    - name: "amazon-eks-node-al2023-x86_64-neuron-1.29-v*"
  role: KarpenterNode-wre-dev
  tags:
    Environment: dev
    karpenter.sh/discovery: wre-dev
    model-inferencing: "inf2-inference"
    ray-control-plane: "false"
    Provisioned-By: aws-solutions-library-samples/guidance-for-automated-provisioning-of-application-ready-amazon-eks-clusters
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      volumeSize: 300Gi
      volumeType: gp3
      iops: 8000
      encrypted: false
      deleteOnTermination: true
      throughput: 256
