model_list: 
        - model_name: unsloth/DeepSeek-R1-Distill-Qwen-7B-GGUF
          litellm_params:
            model: openai/unsloth/DeepSeek-R1-Distill-Qwen-7B-GGUF
            api_base: http://llama-cpp-cpu-lb-2137543273.us-west-2.elb.amazonaws.com/v1
            api_key: os.environ/OPENAI_API_KEY
        - model_name: Qwen/QwQ-32B-AWQ
          litellm_params:
            model: openai/Qwen/QwQ-32B-AWQ
            api_base: http://52.11.105.97:8080/v1
            api_key: os.environ/OPENAI_API_KEY
general_settings: 
            master_key: os.environ/LITELLM_MASTER_KEY